---
triple:          'arm64-apple-darwin'
binary-path:     '/Users/atharvnawal/Desktop/sem3-modul 4/CGAVR/7 Wave (r+1) opengl C/app'
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _drawEllipse, symObjAddr: 0x0, symBinAddr: 0x1000036E8, symSize: 0x51C }
  - { offsetInCU: 0x3F, offset: 0x3F, size: 0x8, addend: 0x0, symName: _dr, symObjAddr: 0x780, symBinAddr: 0x100008000, symSize: 0x0 }
  - { offsetInCU: 0x69, offset: 0x69, size: 0x8, addend: 0x0, symName: _xc, symBinAddr: 0x10000800C, symSize: 0x0 }
  - { offsetInCU: 0x7E, offset: 0x7E, size: 0x8, addend: 0x0, symName: _yc, symBinAddr: 0x100008010, symSize: 0x0 }
  - { offsetInCU: 0x93, offset: 0x93, size: 0x8, addend: 0x0, symName: _rx, symBinAddr: 0x100008004, symSize: 0x0 }
  - { offsetInCU: 0xA8, offset: 0xA8, size: 0x8, addend: 0x0, symName: _ry, symBinAddr: 0x100008008, symSize: 0x0 }
  - { offsetInCU: 0xB1, offset: 0xB1, size: 0x8, addend: 0x0, symName: _drawEllipse, symObjAddr: 0x0, symBinAddr: 0x1000036E8, symSize: 0x51C }
  - { offsetInCU: 0x153, offset: 0x153, size: 0x8, addend: 0x0, symName: _display, symObjAddr: 0x51C, symBinAddr: 0x100003C04, symSize: 0xD8 }
  - { offsetInCU: 0x168, offset: 0x168, size: 0x8, addend: 0x0, symName: _init, symObjAddr: 0x5F4, symBinAddr: 0x100003CDC, symSize: 0x64 }
  - { offsetInCU: 0x17D, offset: 0x17D, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x658, symBinAddr: 0x100003D40, symSize: 0x118 }
...
